# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awry < Formula
  desc "Terminal-based AWS profile manager with a TUI"
  homepage "https://github.com/Art-Thor/awry"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Art-Thor/awry/releases/download/v0.5.0/awry_0.5.0_darwin_amd64.tar.gz"
      sha256 "7d872f8592c5f21b5b7da29f968055d17939d91b1aa6d3a3facbd9a80f774bc2"

      define_method(:install) do
        bin.install "awry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Art-Thor/awry/releases/download/v0.5.0/awry_0.5.0_darwin_arm64.tar.gz"
      sha256 "467ac40ad0e2c5f5be3133ae6687f3a921b171c72e689e1c541405d667241b6c"

      define_method(:install) do
        bin.install "awry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Art-Thor/awry/releases/download/v0.5.0/awry_0.5.0_linux_amd64.tar.gz"
      sha256 "9f0ef0d5c426ceae0ae70273889d77f6840e03aa44f4484e852ad455002bef25"
      define_method(:install) do
        bin.install "awry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Art-Thor/awry/releases/download/v0.5.0/awry_0.5.0_linux_arm64.tar.gz"
      sha256 "9736437648c522c71eee1453c009157e9d84eeffb44a91ded1172807d1086fbc"
      define_method(:install) do
        bin.install "awry"
      end
    end
  end

  test do
    system "#{bin}/awry", "--help"
  end
end
