# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awry < Formula
  desc "Terminal-based AWS profile manager with a TUI"
  homepage "https://github.com/Art-Thor/awry"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Art-Thor/awry/releases/download/v0.4.6/awry_0.4.6_darwin_amd64.tar.gz"
      sha256 "fa6f63282e8bf55efff441433da916db149943adfe455b6234742ca4f0a95d35"

      define_method(:install) do
        bin.install "awry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Art-Thor/awry/releases/download/v0.4.6/awry_0.4.6_darwin_arm64.tar.gz"
      sha256 "3eb8d2aa5668da06134b8714598f9b8c8c322d3cafae2d124863d321460303d3"

      define_method(:install) do
        bin.install "awry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Art-Thor/awry/releases/download/v0.4.6/awry_0.4.6_linux_amd64.tar.gz"
      sha256 "9f77f20e8becbfc567c5f8ae6d40630b4234bf1385574a9d3dc12cd4e37b6791"
      define_method(:install) do
        bin.install "awry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Art-Thor/awry/releases/download/v0.4.6/awry_0.4.6_linux_arm64.tar.gz"
      sha256 "7bfac2079659ae4d82964b6893e4a572e3f788b641f24e48614dc7c86a225a29"
      define_method(:install) do
        bin.install "awry"
      end
    end
  end

  test do
    system "#{bin}/awry", "--help"
  end
end
